[package]
name = "simd_hex"
version = "0.1.0"
authors = ["lassade"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# bench basic support
rand = "0.7"
criterion = "0.3"

# compasition
hex = "0.4.2"
base16 = "0.2.1"
faster-hex = "0.4.1"
base64 = "0.12.3"
b64-ct = "0.1.1"

[[bench]]
name = "bench"
harness = false